---
# This playbook configures other roles

- name: setup ldap server role
  hosts: role_ldap_server
  become: yes
  become_user: root
  roles:
    - ldap_server

- name: setup staging server role
  hosts: role_staging_server
  become: yes
  become_user: root
  roles:
    - role: splunk_software
      vars:
        splunk_install_app: splunk