---
splunk_env_name: gsocsan
splunk_version: latest
splunk_admin_password: spaslajs093jsl02
splunk_outputs: all
splunk_search_peers: all
splunk_secret_share:
  splunk: false
  splunkforwarder: false
  equal: false
splunk_volume_defaults:
  homePath: hot
  coldPath: cold
splunk_ssl:
  web:
    enable: true
    own_certs: false
    config:
      enableSplunkWebSSL: true
  inputs:
    enable: true
    own_certs: false
    config:
      rootCA: "$SPLUNK_HOME/etc/auth/cacert.pem"
      serverCert: "$SPLUNK_HOME/etc/auth/server.pem"
      sslPassword: password
  outputs:
    enable: true
    own_certs: false
    config:
      sslRootCAPath: "$SPLUNK_HOME/etc/auth/cacert.pem"
      sslCertPath: "$SPLUNK_HOME/etc/auth/server.pem"
      sslPassword: password
splunk_license_file: Splunk_Enterprise.lic
splunk_loginpage_print_hostname: false
splunk_loginpage_print_userpw: false
splunk_loginpage_print_roles: false
